name: CI

on: [push]

jobs:
    build:
        runs-on: macos-latest
        # strategy:
        #     matrix:
        #         run-config:
        #             - { scheme: "Clendar", destination: "platform=macOS" }
        #             - {
        #                   scheme: "Clendar",
        #                   destination: "platform=iOS Simulator,OS=15.0.0,name=iPhone 13",
        #               }

        steps:
            # - name: Checkout Project
            #   uses: actions/checkout@v1

            # - name: Homebrew build helpers install
            #   run: brew bundle

            - name: Show the currently detailed version of Xcode for CLI
              run: xcode-select -p

            - name: Show what's in Applications
              run: ls -al /Applications

            # - name: Switch to Xcode 13
            #   run: sudo xcode-select -s /Applications/Xcode_13.app

            # - name: Show Build Settings
            #   run: xcodebuild -workspace Clendar.xcworkspace -scheme '${{ matrix.run-config['scheme'] }}' -showBuildSettings

            # - name: Show Build SDK
            #   run: xcodebuild -workspace Clendar.xcworkspace -scheme '${{ matrix.run-config['scheme'] }}' -showsdks

            # - name: Show Available Destinations
            #   run: xcodebuild -workspace Clendar.xcworkspace -scheme '${{ matrix.run-config['scheme'] }}' -showdestinations

            # - name: lint
            #   run: swift format lint --configuration .swift-format-config -r .

            # - name: build and test
            #   run: xcodebuild clean test -scheme '${{ matrix.run-config['scheme'] }}' -destination '${{ matrix.run-config['destination'] }}' -showBuildTimingSummary
